Make dystonse-gtfs-importer a universal tool
dystonse/dystonse-gtfs-data pull request #1
Opened 2020-04-07 08:04 UTC by lenaschimmel

This PR makes `import` a command within `dystonse-gtfs-tool` and adds a new `analyse` command (which does nothing yet).

If we change it that way, of course we should also rename the repository from `dystonse-gtfs-importer` to `dystonse-gtfs-tool` and adapt the Docker setup.

2020-04-08 22:43 UTC, flauschzelle requested changes

2020-04-08 22:43 UTC, flauschzelle commented on README.md
> +This is a Rust crate that works with a static gtfs schedules (as zip or directory), gtfs-realtime data (as .pb or .zip files) and a mysql database (setup info is specified in [dystonse-docker](https:
```suggestion
This is a Rust crate that works with static gtfs schedules (as zip or directory), gtfs-realtime data (as .pb or .zip files) and a mysql database (setup info is specified in [dystonse-docker](https://github.com/dystonse/dystonse-docker)) to read, import or anaylse the data.
```

2020-04-08 22:43 UTC, flauschzelle commented on README.md
> +# dystonse-gtfs-tool
"Tool" is a very nondescript name... the name should be indicating what this tool is for. It has more than one use case obviously, but what do all the uses have in common that makes it necessary to keep them together in one crate? Maybe they all have to access the database directly (and provide interfaces for any other part of our software that might want to use data from the database)? Then we could call it `dystonse-gtfs-db` or `dystonse-gtfs-database` or maybe even `dystonse-gtfs-data`...

2020-04-08 22:43 UTC, flauschzelle commented on src/analyser/mod.rs
> +                    Successfully processed files are moved to a subdirectory named 'imported'. \
This needs to be updated, it still uses the old text (of the importer).

2020-04-08 22:43 UTC, flauschzelle commented on src/analyser/mod.rs
> +        let step = Duration::hours(1);
make this a constant or an argument to be input by the user

2020-04-08 22:43 UTC, flauschzelle commented on src/importer/mod.rs
> +    schedule_dir: Option<String>,    target_dir: Option<String>,
```suggestion
    schedule_dir: Option<String>,    
    target_dir: Option<String>,
```

2020-04-08 22:43 UTC, flauschzelle commented on src/main.rs
> +    let matches = App::new("Dystonse GTFS Tool")
use kebap-case here (and change the name, see comments above for that)

2020-04-10 21:43 UTC, lenaschimmel commented
I think I implemented all of your requests.

2020-04-10 22:22 UTC, merged